name: flutter_billing_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  intl: ^0.18.1
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.2
  cross_file: ^0.3.4+2
  file_selector: ^1.0.3
  sqflite_common_ffi: ^2.3.6
  open_filex: ^4.7.0
  logging: ^1.2.0
  provider: ^6.1.5+1
  responsive_builder: ^0.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Nunito-Regular.ttf
    - assets/fonts/Nunito-Bold.ttf
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
